deployments:
  spark-xprize-plugin:
    replicaCount: 1
    podAnnotations:
      vatom/commit-sha: "{{ tpl .Values.commitSha . }}"
    containers:
      spark-xprize-plugin:
        image: us-docker.pkg.dev/u-repo-161-artifact/vatom-artifact-docker-us/spark-xprize-plugin:{{ tpl .Values.commitSha . }}
        imagePullPolicy: IfNotPresent
        command:
          - yarn
          - -s
          - start
        containerPorts:
          - containerPort: 3000
            protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    terminationGracePeriodSeconds: 30

services:
  spark-xprize-plugin:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000

ingresses:
  spark-xprize-plugin:
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    rules:
      - host: xprize-plugin.api.vatominc.cc
        http:
          paths:
          - backend:
              service:
                name: spark-xprize-plugin
                port:
                  number: 3000
            path: /
            pathType: Prefix